### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by leezhuuu** [disingn/sunotoapi#12]
t@ecs3Im1:/leezhu/sunotoapi# /leezhu/sunotoapi/fksunoapi
 ┌───────────────────────────────────────────────────┐
 │                   Fiber v2.52.3                   │
 │               http://127.0.0.1:3560               │
 │       (bound on host 0.0.0.0 and port 3560)       │
 │                                                   │
 │ Handlers ............. 7  Processes ........... 1 │
 │ Prefork ....... Disabled  PID ............ 119374 │
 └───────────────────────────────────────────────────┘
panic: runtime error: index out of range [0] with length 0
goroutine 22 [running]:
fksunoapi/serve.GetSession({0xc0000c0367, 0xa})
        /leezhu/sunotoapi/serve/serve.go:70 +0x537
fksunoapi/router.SunoChat.func1(0xc000178000)
        /leezhu/sunotoapi/router/router.go:81 +0xa5
github.com/gofiber/fiber/v2.(*App).next(0xc000138a00, 0xc000178000)
        /root/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.3/router.go:145 +0x1bf
github.com/gofiber/fiber/v2.(*Ctx).Next(0x0?)
        /root/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.3/ctx.go:1030 +0x53
github.com/gofiber/fiber/v2/middleware/cors.New.func1(0xc0000a4990?)
        /root/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.3/middleware/cors/cors.go:168 +0x1b4
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc00013e930?)
        /root/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.3/ctx.go:1027 +0x43
github.com/gofiber/fiber/v2/middleware/logger.New.func3(0xc000178000)
        /root/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.3/middleware/logger/logger.go:119 +0x325
github.com/gofiber/fiber/v2.(*App).next(0xc000138a00, 0xc000178000)
        /root/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.3/router.go:145 +0x1bf
github.com/gofiber/fiber/v2.(*App).handler(0xc000138a00, 0x483c57?)
        /root/go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.3/router.go:172 +0x87
github.com/valyala/fasthttp.(*Server).serveConn(0xc0000f8200, {0x8f9a18?, 0xc0000b4260})
        /root/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/server.go:2359 +0x11d3
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00014a1e0, 0xc000098840)
        /root/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/workerpool.go:224 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        /root/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/workerpool.go:196 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /root/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/workerpool.go:195 +0x1b0
root@ecs3Im1:/leezhu/sunotoapi#
root@ecs3Im1:/leezhu/sunotoapi#

build之后出现这个错误，请debug一下

**Comment by leezhuuu** [comment]
错误信息指出你的Go程序在运行时遇到了一个panic，原因是"index out of range [0] with length 0"。这意味着程序试图访问一个长度为0的数组或切片的第一个元素，这是不可能的。具体来说，这发生在`serve.go`文件的`GetSession`函数中，以及在`router.go`文件的`SunoChat`函数中调用该函数的地方。

这个问题通常是因为代码没有正确地处理空数组或切片的情况。为了解决这个问题，你需要检查涉及的函数，确保在访问数组或切片元素之前，数组或切片是有元素的。

### 解决方案

1. **检查`GetSession`函数**：在`serve/serve.go`中的`GetSession`函数里，你需要找到所有试图访问数组或切片元素的代码行，然后在这些操作之前检查数组或切片的长度。

例如，如果`GetSession`函数中有类似于`someSlice[0]`的代码行，你需要在这之前加入一个检查：

```go
if len(someSlice) == 0 {
    // 处理空切片的情况，比如返回一个错误或默认值
    return nil, errors.New("someSlice is empty")
}
```

2. **检查`SunoChat`函数调用`GetSession`的方式**：在`router/router.go`的`SunoChat`函数中，确保处理了`GetSession`可能返回的错误。

例如，如果`GetSession`现在返回一个错误（基于上述修改），你需要检查并处理这个错误：

```go
session, err := GetSession(args)
if err != nil {
    // 适当地处理错误，比如返回错误响应
    return
}
```

3. **重新编译并运行你的程序**：做完上述更改后，重新编译你的Go程序并运行它。这应该会解决panic的问题，使你的程序能够在遇到空数组或切片时优雅地处理，而不是崩溃。

记得在修改代码后进行彻底的测试，确保这些更改没有引入新的问题，并且现有的功能仍然按预期工作。


这个是gpt的解释

**Comment by qq137321** [comment]
是的，我的也一样的错误。不知道怎么解决

**Comment by linxp001** [comment]
我觉得额应该是参数里放置有效的cookie就可以了，如果cookie过期了或者取错了就会报这个错。
